# on:
#   schedule:
#     - cron: '25 8 * * *' # 8:25 AM every day
#       timezone: 'America/Chicago'

on: 
  workflow_dispatch:

jobs: 
  run_main:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync

    - name: Run my code
      run: uv run ./src/main.py ${{ secrets.USGS_API_KEY }}

    - name: Git push map updates to the repo
      run: 
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/daily content 
          git commit -m "update data and map htmls - github action" || echo "No changes to commit"

          git push