on:
  workflow_dispatch:

  schedule:
    - cron: '21 7 * * *' # 7:21 AM every day
      timezone: 'America/Chicago'

jobs: 
  run_main:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync

    - name: Run main.py
      run: |
        uv run ./src/main.py ${{ secrets.USGS_API_KEY }} || 
        Start-Sleep -Seconds 5; uv run ./src/main.py ${{ secrets.USGS_API_KEY }}

    - name: Git push data and map updates to the repo
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add content data/daily
          git commit -m "update data and map htmls - github action" || echo "No changes to commit"

          git push